"""Desktop layouts; recording and storage remain in the application controller."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QCheckBox, QComboBox, QDoubleSpinBox, QFormLayout,
    QFrame, QGridLayout, QHBoxLayout, QLineEdit, QProgressBar, QScrollArea, QSpinBox,
    QTextEdit, QVBoxLayout, QWidget)
from .design import ShieldArt, Timeline, button, card, label, table
from .product import PRESETS


def scroll_page():
    scroll = QScrollArea()
    scroll.setWidgetResizable(True)
    page = QWidget()
    page.setObjectName("content")
    box = QVBoxLayout(page)
    box.setContentsMargins(0, 0, 3, 0)
    box.setSpacing(16)
    scroll.setWidget(page)
    return scroll, box


def metric_strip(entries):
    layout = QHBoxLayout()
    layout.setSpacing(12)
    values, captions = [], []
    for index, (title, value, caption) in enumerate(entries):
        widget, box = card()
        box.setContentsMargins(18, 14, 18, 14)
        box.setSpacing(4)
        box.addWidget(label(title, "eyebrow"))
        metric = label(value, "metricAccent" if index == 0 else "metricValue")
        text = label(caption, "muted")
        box.addWidget(metric)
        box.addWidget(text)
        values.append(metric)
        captions.append(text)
        layout.addWidget(widget, 1)
    return layout, values, captions


def overview_page(w):
    scroll, layout = scroll_page()
    hero = QFrame()
    hero.setObjectName("hero")
    hero_box = QHBoxLayout(hero)
    hero_box.setContentsMargins(30, 26, 20, 26)
    text = QVBoxLayout()
    text.setSpacing(12)
    text.addWidget(label("QORGAU / EXAM INTELLIGENCE", "heroTag"))
    text.addWidget(label("Честный экзамен.\nУверенное решение.", "heroTitle"))
    text.addWidget(label("Наблюдение, понятные сигналы и проверка человеком.\nВсё в одном рабочем пространстве.", "heroText"))
    actions = QHBoxLayout()
    actions.addWidget(button("Новый экзамен   →", lambda: w.navigate(0), "heroButton"))
    actions.addWidget(button("Показать демо", w.launch_demo, "heroSecondary"))
    actions.addStretch()
    text.addLayout(actions)
    hero_box.addLayout(text, 3)
    hero_box.addWidget(ShieldArt(), 1)
    layout.addWidget(hero)
    metrics, w.overview_values, _ = metric_strip([
        ("ЭКЗАМЕНЫ", "0", "Реальные сессии"), ("ЗАВЕРШЕНЫ", "0", "Сохранены в истории"),
        ("ВРЕМЯ НАБЛЮДЕНИЯ", "0 мин", "По реальным сессиям"), ("СОБЫТИЯ", "0", "Для проверки человеком")])
    layout.addLayout(metrics)
    middle = QHBoxLayout()
    recent, box = card()
    head = QHBoxLayout()
    head.addWidget(label("Последние сессии", "cardTitle"))
    head.addStretch()
    head.addWidget(button("Вся история  →", lambda: w.navigate(1)))
    box.addLayout(head)
    w.recent_table = table(["Участник / экзамен", "Режим", "События", "Статус"])
    w.recent_table.setMinimumHeight(175)
    w.recent_table.cellDoubleClicked.connect(w.open_recent)
    box.addWidget(w.recent_table)
    w.recent_empty = label("Ваша первая сессия появится здесь.\nНачните экзамен или познакомьтесь с продуктом в деморежиме.", "empty")
    box.addWidget(w.recent_empty)
    middle.addWidget(recent, 3)
    capabilities, box = card("Три уровня наблюдения")
    for number, title, detail in (
        ("01", "Камера и AI", "Телефон, люди, отсутствие и поворот головы"),
        ("02", "Действия на компьютере", "Окна и четыре сочетания клавиш"),
        ("03", "Решение проверяющего", "Хронология, подтверждение и отчёт")):
        row = QHBoxLayout()
        number_label = label(number, "number")
        number_label.setFixedWidth(32)
        row.addWidget(number_label, 0, Qt.AlignmentFlag.AlignTop)
        texts = QVBoxLayout()
        texts.setSpacing(4)
        texts.addWidget(label(title, "cardTitle"))
        texts.addWidget(label(detail, "muted"))
        row.addLayout(texts, 1)
        box.addLayout(row)
    middle.addWidget(capabilities, 2)
    layout.addLayout(middle)
    w.overview_note = label("Демонстрационные сессии помечены отдельно и не входят в статистику реальных экзаменов.", "muted")
    layout.addWidget(w.overview_note)
    layout.addStretch()
    return scroll


def monitor_page(w, preview_class):
    scroll, layout = scroll_page()
    metrics, w.metrics, w.metric_captions = metric_strip([
        ("ВРЕМЯ СЕССИИ", "00:00:00", "Ожидание старта"), ("СОБЫТИЯ", "0", "Требуют просмотра"),
        ("ИНДЕКС ПРОВЕРКИ", "0 / 100", "Приоритет, а не вердикт"), ("ЛЮДИ В КАДРЕ", "—", "Источник не подключён")])
    layout.addLayout(metrics)
    middle = QHBoxLayout()
    middle.setSpacing(16)
    camera, camera_box = card()
    camera.setObjectName("videoCard")
    camera_box.setContentsMargins(18, 16, 18, 14)
    camera_top = QHBoxLayout()
    camera_top.addWidget(label("LIVE OBSERVATION", "cardTitle"))
    camera_top.addStretch()
    w.camera_info = label("OFFLINE", "cameraState")
    camera_top.addWidget(w.camera_info)
    camera_box.addLayout(camera_top)
    w.preview = preview_class()
    camera_box.addWidget(w.preview, 1)
    w.demo_banner = label("ДЕМО · Синтетический сценарий / 48 секунд", "banner")
    w.demo_banner.hide()
    camera_box.addWidget(w.demo_banner)
    w.pipeline_info = label("Подключите камеру — анализ начнётся после загрузки моделей.", "muted")
    camera_box.addWidget(w.pipeline_info)
    middle.addWidget(camera, 3)
    controls, controls_box = card()
    controls.setMinimumWidth(275)
    controls.setMaximumWidth(310)
    controls_box.setSpacing(8)
    controls_box.addWidget(label("НОВАЯ СЕССИЯ", "eyebrow"))
    controls_box.addWidget(label("Всё готово к старту?", "cardTitle"))
    w.candidate = QLineEdit()
    w.candidate.setMaxLength(120)
    w.candidate.setPlaceholderText("ФИО или ID участника")
    w.candidate.setAccessibleName("Участник экзамена")
    w.exam = QLineEdit()
    w.exam.setMaxLength(160)
    w.exam.setPlaceholderText("Название экзамена")
    w.exam.setAccessibleName("Название экзамена")
    w.mode = QComboBox()
    w.mode.addItems(["Реальная камера", "Демонстрация"])
    w.mode.setAccessibleName("Режим наблюдения")
    form = QFormLayout()
    form.setSpacing(9)
    for caption, widget in (("Участник", w.candidate), ("Экзамен", w.exam), ("Источник", w.mode)):
        form.addRow(label(caption, "muted"), widget)
    controls_box.addLayout(form)
    w.connect_button = button("Подключить камеру", w.connect_camera)
    controls_box.addWidget(w.connect_button)
    w.bind_button = button("Выбрать окно экзамена", w.bind_window)
    w.bind_button.setToolTip("Внешнее окно: переключитесь в него за 5 секунд. По умолчанию отслеживается выход из QORGAU AI.")
    controls_box.addWidget(w.bind_button)
    w.readiness = label("Подключите источник и заполните данные", "readiness")
    controls_box.addWidget(w.readiness)
    actions = QHBoxLayout()
    actions.setSpacing(8)
    w.start_button = button("Начать   →", w.start_session, "primary")
    w.start_button.setEnabled(False)
    actions.addWidget(w.start_button)
    w.stop_button = button("Завершить", w.stop_session, "danger")
    w.stop_button.setEnabled(False)
    actions.addWidget(w.stop_button)
    controls_box.addLayout(actions)
    controls_box.addStretch()
    middle.addWidget(controls, 2)
    layout.addLayout(middle)
    security, security_box = card()
    security_box.setContentsMargins(18, 12, 18, 12)
    row = QHBoxLayout()
    w.window_info = label("ОКНА · выход из QORGAU AI", "muted")
    w.keyboard_info = label("КЛАВИШИ · контроль включится с началом экзамена", "muted")
    row.addWidget(w.window_info, 1)
    row.addWidget(w.keyboard_info, 1)
    security_box.addLayout(row)
    layout.addWidget(security)
    w.status = label("Введите данные участника и подключите источник.", "status")
    layout.addWidget(w.status)
    timeline_card, box = card()
    header = QHBoxLayout()
    header.addWidget(label("Хронология сессии", "cardTitle"))
    header.addStretch()
    header.addWidget(label("Нажмите на отметку, чтобы выбрать событие", "muted"))
    box.addLayout(header)
    w.timeline = Timeline()
    w.timeline.eventSelected.connect(w.select_timeline_event)
    box.addWidget(w.timeline)
    layout.addWidget(timeline_card)
    journal, box = card()
    row = QHBoxLayout()
    row.addWidget(label("Лента событий", "cardTitle"))
    row.addStretch()
    w.journal_search = QLineEdit()
    w.journal_search.setPlaceholderText("Найти событие…")
    w.journal_search.setAccessibleName("Поиск событий текущей сессии")
    w.journal_search.setMaximumWidth(220)
    w.journal_filter = QComboBox()
    w.journal_filter.setAccessibleName("Категория событий")
    for title, category in (("Все события", "all"), ("Камера", "vision"), ("Клавиши", "keyboard"), ("Окна", "window"), ("Технические", "technical")):
        w.journal_filter.addItem(title, category)
    row.addWidget(w.journal_search)
    row.addWidget(w.journal_filter)
    box.addLayout(row)
    w.event_table = table(["Время", "Событие", "Длительность", "Состояние"])
    w.event_table.setMinimumHeight(175)
    w.event_table.setMaximumHeight(230)
    box.addWidget(w.event_table)
    w.journal_empty = label("Пока всё спокойно. Зарегистрированные события появятся здесь.", "empty")
    box.addWidget(w.journal_empty)
    layout.addWidget(journal)
    w.mode.currentIndexChanged.connect(w.mode_changed)
    w.candidate.textChanged.connect(w.update_readiness)
    w.exam.textChanged.connect(w.update_readiness)
    w.journal_search.textChanged.connect(w.filter_journal)
    w.journal_filter.currentIndexChanged.connect(w.filter_journal)
    return scroll


def archive_page(w):
    scroll, layout = scroll_page()
    top = QHBoxLayout()
    w.search = QLineEdit()
    w.search.setPlaceholderText("Поиск по участнику или экзамену…")
    w.search.setAccessibleName("Поиск сохранённых сессий")
    w.search.textChanged.connect(w.refresh_sessions)
    w.archive_filter = QComboBox()
    for title, key in (("Все сессии", "all"), ("Реальные", "live"), ("Демо", "demo"), ("Прерванные", "interrupted")):
        w.archive_filter.addItem(title, key)
    w.archive_filter.currentIndexChanged.connect(w.refresh_sessions)
    top.addWidget(w.search, 1)
    top.addWidget(w.archive_filter)
    top.addWidget(button("Обновить", w.refresh_sessions))
    layout.addLayout(top)
    sessions, box = card()
    w.sessions_table = table(["ID", "Участник / экзамен", "Начало", "Источник", "События", "Статус"])
    w.sessions_table.setMinimumHeight(145)
    w.sessions_table.setMaximumHeight(225)
    w.sessions_table.itemSelectionChanged.connect(w.select_session)
    box.addWidget(w.sessions_table)
    w.archive_empty = label("Нет сохранённых сессий. Создайте экзамен или запустите демонстрацию.", "empty")
    box.addWidget(w.archive_empty)
    layout.addWidget(sessions)
    events, box = card("Рабочее место проверяющего")
    w.review_summary = label("Выберите сессию, чтобы изучить её хронологию.", "muted")
    box.addWidget(w.review_summary)
    w.review_progress = QProgressBar()
    w.review_progress.setRange(0, 100)
    box.addWidget(w.review_progress)
    w.review_counts = label("Проверено 0 из 0", "muted")
    box.addWidget(w.review_counts)
    w.review_timeline = Timeline()
    w.review_timeline.eventSelected.connect(w.review_table_select)
    box.addWidget(w.review_timeline)
    w.review_table = table(["Время", "Событие", "Длительность", "Решение", "Детали"])
    w.review_table.setMinimumHeight(185)
    box.addWidget(w.review_table)
    actions = QHBoxLayout()
    w.review_actions = []
    for caption, verdict in (("Подтвердить", "confirmed"), ("Отклонить", "dismissed"), ("Сбросить", "pending")):
        action = button(caption, lambda checked=False, v=verdict: w.review_event(v))
        actions.addWidget(action)
        w.review_actions.append(action)
    w.evidence_button = button("Открыть кадр", w.open_evidence)
    actions.addWidget(w.evidence_button)
    w.review_actions.append(w.evidence_button)
    actions.addStretch()
    box.addLayout(actions)
    w.review_table.itemSelectionChanged.connect(w.update_review_actions)
    w.note = QTextEdit()
    w.note.setPlaceholderText("Вывод проверяющего — будет включён в отчёт")
    w.note.setMinimumHeight(75)
    w.note.setMaximumHeight(100)
    box.addWidget(w.note)
    footer = QHBoxLayout()
    w.save_note_button = button("Сохранить вывод", w.save_note)
    footer.addWidget(w.save_note_button)
    footer.addStretch()
    w.export_button = button("Экспорт отчёта   ↓", w.export_selected, "primary")
    footer.addWidget(w.export_button)
    box.addLayout(footer)
    layout.addWidget(events)
    w.archive_status = label("HTML для печати / PDF · CSV для таблиц · JSON для данных", "muted")
    layout.addWidget(w.archive_status)
    return scroll


def settings_page(w):
    scroll, layout = scroll_page()
    presets, box = card("Выберите профиль наблюдения")
    box.addWidget(label("Профиль меняет задержки и угол головы. Номер камеры, уверенность моделей и сохранение кадров остаются вашими.", "muted"))
    row = QHBoxLayout()
    w.preset_buttons = []
    for key, (title, _) in PRESETS.items():
        control = button(title, lambda checked=False, p=key: w.apply_preset(p))
        w.preset_buttons.append(control)
        row.addWidget(control)
    box.addLayout(row)
    w.preset_hint = label("Изменения вступят в силу после сохранения и следующего подключения.", "muted")
    box.addWidget(w.preset_hint)
    layout.addWidget(presets)
    groups = QHBoxLayout()
    detection, detection_box = card("Камера и детекция")
    timing, timing_box = card("Когда регистрировать событие")
    detection_form, timing_form = QFormLayout(), QFormLayout()
    for form in (detection_form, timing_form):
        form.setSpacing(14)
    w.setting_fields = {}
    options = [("camera_index", "Номер камеры", 0, 9, 1),
        ("confidence", "Уверенность: человек", .1, .95, .05), ("phone_confidence", "Уверенность: телефон", .1, .95, .05),
        ("head_angle", "Поворот головы, °", 10, 80, 5), ("phone_seconds", "Телефон — задержка, с", .5, 60, .5),
        ("multiple_seconds", "Несколько людей — задержка, с", .5, 60, .5), ("absence_seconds", "Отсутствие — задержка, с", .5, 60, .5),
        ("head_seconds", "Поворот головы — задержка, с", .5, 60, .5), ("window_seconds", "Выход из окна — задержка, с", 0, 60, .5)]
    for key, caption, minimum, maximum, step in options:
        field = QSpinBox() if key == "camera_index" else QDoubleSpinBox()
        field.setRange(minimum, maximum)
        field.setSingleStep(step)
        field.setValue(getattr(w.settings, key))
        field.setAccessibleName(caption)
        field.setMaximumWidth(140)
        w.setting_fields[key] = field
        form = timing_form if key.endswith("_seconds") else detection_form
        form.addRow(label(caption, "muted"), field)
    detection_box.addLayout(detection_form)
    detection_box.addWidget(label("Уверенность помогает отсеять слабые распознавания. Угол головы измеряет ориентацию лица, а не направление взгляда.", "muted"))
    detection_box.addStretch()
    timing_box.addLayout(timing_form)
    timing_box.addWidget(label("0 секунд для окон — без дополнительной задержки. Клавиши регистрируются сразу.", "muted"))
    groups.addWidget(detection, 1)
    groups.addWidget(timing, 1)
    layout.addLayout(groups)
    privacy, box = card("Данные под вашим контролем")
    w.evidence_check = QCheckBox("Сохранять один кадр визуального события")
    w.evidence_check.setChecked(w.settings.save_evidence)
    box.addWidget(w.evidence_check)
    box.addWidget(label("По умолчанию кадры выключены. Текст, экран и буфер обмена не собираются. Данные остаются на этом компьютере.", "muted"))
    row = QHBoxLayout()
    w.save_settings_button = button("Сохранить настройки", w.save_settings, "primary")
    row.addWidget(w.save_settings_button)
    row.addStretch()
    row.addWidget(button("Открыть папку данных", w.open_data_folder))
    box.addLayout(row)
    layout.addWidget(privacy)
    layout.addStretch()
    return scroll
